### ISSUE TITLE
使用“./client -p SS服务端端口 -d xxxxxxxxxx >> /dev/null &”出现的问题

### ISSUE THREAD

**Issue by dhengyi** [Jungzhang/HttpWarp#1]
1. 在 Mac 的 zsh 下，使用如上命令，在翻墙的过程中终端仍会打印出大量信息；
2. 命令表示的是后台运行，然而关闭终端后将无法翻墙。

望解答~

**Comment by Jungzhang** [comment]
nohup  ./client -p SS服务端端口 -d xxxxxxx >> /dev/null 2>&1 &    这样呢
